export const news = [
  {
    id: "1",
    title: "Raf Simons Exits Prada After Seven Years",
    summary: "The creative director steps down following the SS25 show, ending a transformative partnership that redefined modern luxury. The departure marks the end of an era for the Italian house.",
    brand: "Prada",
    category: "Business",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    source: "Vogue",
    publishedAt: "2024-03-18T10:00:00Z",
    whyItMatters: "The departure signals a potential shift in luxury fashion leadership structure.",
  },
  {
    id: "2",
    title: "Paris Fashion Week SS25: The Return of Elegance",
    summary: "A season of refined silhouettes and timeless aesthetics emerges across major houses, signaling a departure from the oversized trends that dominated recent seasons.",
    brand: "Various",
    category: "Runway",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=300&fit=crop",
    source: "Vogue",
    publishedAt: "2024-03-17T14:00:00Z",
    whyItMatters: "Oversized trends may finally give way to tailored, classic cuts.",
  },
  {
    id: "3",
    title: "Sabato De Sarno's First Year: A Review",
    summary: "Analyzing the impact of the creative director's minimalist vision on the brand's trajectory and what it means for the future of heritage houses.",
    brand: "Gucci",
    category: "Analysis",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop",
    source: "Elle",
    publishedAt: "2024-03-16T09:00:00Z",
    whyItMatters: "Gucci's new direction sets benchmarks for heritage brands.",
  },
  {
    id: "4",
    title: "Miu Miu's New Collection Breaks Sales Records",
    summary: "The latest drop from Miu Miu sells out within hours, confirming the brand's position as the most coveted label among Gen Z consumers.",
    brand: "Miu Miu",
    category: "Business",
    image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=400&h=300&fit=crop",
    source: "Bazaar",
    publishedAt: "2024-03-15T16:00:00Z",
    whyItMatters: "Miu Miu continues to dominate the conversation in luxury fashion.",
  },
  {
    id: "5",
    title: "JW Anderson SS25: Playful Proportions",
    summary: "Jonathan Anderson presents another thought-provoking collection featuring exaggerated silhouettes and unexpected fabric combinations.",
    brand: "JW Anderson",
    category: "Runway",
    image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400&h=300&fit=crop",
    source: "Vogue Runway",
    publishedAt: "2024-03-14T12:00:00Z",
    whyItMatters: "Anderson continues to push boundaries in contemporary fashion.",
  },
  {
    id: "6",
    title: "Balenciaga's New Era Under Demna",
    summary: "The creative director unveils a more refined approach, moving away from controversial stunts toward純粋な fashion statements.",
    brand: "Balenciaga",
    category: "Runway",
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=400&h=300&fit=crop",
    source: "Vogue",
    publishedAt: "2024-03-13T11:00:00Z",
    whyItMatters: "A shift in direction for one of fashion's most talked-about brands.",
  },
  {
    id: "7",
    title: "Sustainable Fashion Week Launches in Milan",
    summary: "A new event dedicated entirely to sustainable fashion brands kicks off, featuring 50 eco-conscious designers.",
    brand: "Industry",
    category: "Sustainability",
    image: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&h=300&fit=crop",
    source: "Cosmopolitan",
    publishedAt: "2024-03-12T08:00:00Z",
    whyItMatters: "Sustainability continues to gain traction in high fashion.",
  },
  {
    id: "8",
    title: "Louis Vuitton Names New Creative Director",
    summary: "The luxury giant appoints a surprising choice as the successor to Virgil Abloh, signaling a new chapter for the maison.",
    brand: "Louis Vuitton",
    category: "Business",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=300&fit=crop",
    source: "GQ",
    publishedAt: "2024-03-11T15:00:00Z",
    whyItMatters: "The appointment could redefine the future of the iconic house.",
  },
];

export const sources = [
  { id: "1", name: "Vogue", type: "Magazine", url: "https://vogue.com" },
  { id: "2", name: "Gucci", type: "House", url: "https://gucci.com" },
  { id: "3", name: "Prada", type: "House", url: "https://prada.com" },
  { id: "4", name: "Balenciaga", type: "House", url: "https://balenciaga.com" },
  { id: "5", name: "Elle", type: "Magazine", url: "https://elle.com" },
  { id: "6", name: "Bazaar", type: "Magazine", url: "https://harpersbazaar.com" },
  { id: "7", name: "Farfetch", type: "Retailer", url: "https://farfetch.com" },
  { id: "8", name: "Net-a-Porter", type: "Retailer", url: "https://net-a-porter.com" },
  { id: "9", name: "Vogue Runway", type: "Platform", url: "https://vogue.com/fashion-week" },
  { id: "10", name: "JW Anderson", type: "House", url: "https://jw-anderson.com" },
  { id: "11", name: "Miu Miu", type: "House", url: "https://miumiu.com" },
  { id: "12", name: "StockX", type: "Platform", url: "https://stockx.com" },
];

export const categories = [
  { id: "1", name: "Runway", icon: "👗" },
  { id: "2", name: "Business", icon: "💼" },
  { id: "3", name: "Analysis", icon: "📊" },
  { id: "4", name: "Sustainability", icon: "🌱" },
  { id: "5", name: "Streetwear", icon: "👟" },
  { id: "6", name: "High Jewelry", icon: "💎" },
  { id: "7", name: "Men's", icon: "👔" },
  { id: "8", name: "Women's", icon: "👗" },
];
